### ISSUE TITLE
Bookmarks are encrypted when PDF is secured via PdfSecuritySettings

### ISSUE THREAD

**Issue by LaszloKoller** [empira/PDFsharp-1.5#1]
There appears to be an issue with bookmarks when a PDF document is encrypted via _PdfSecuritySettings_.

Take the example of adding a bookmark to a newly built PDF [via the _AddBookmark()_ method] using MigraDoc. After that PDF is rendered [via the _PdfDocumentRenderer.RenderDocument()_ method] if a password is set in the _OwnerPassword_ property via the _PdfSecuritySettings_ object in order to secure the PDF (and the _DocumentSecurityLevel_ property is set to _PdfDocumentSecurityLevel.Encrypted128Bit_), then all bookmark text appears encrypted in the final, saved PDF when viewed via Adobe Acrobat. If a MigraDoc-constructed PDF is not secured, then bookmark text appears in clear text when viewed via Adobe Acrobat.

As a control, if a PDF is manually secured (by adding an owner password, for example) while using Adobe Acrobat, then bookmark text in that PDF remains readable (i.e., in clear text when viewed via Adobe Acrobat).

**Comment by dpieski** [comment]
Just an example showing what he is saying. The PDF is readable but the Bookmarks are not decrypted.
(And this was with a dfferent reader than Adobe.)

![2017-02-27 13_08_58-client - 1 pdf secured - foxit reader](https://cloud.githubusercontent.com/assets/3300522/23375446/0868fd4a-fcee-11e6-92c3-1b04a15a5efc.png)

**Comment by TH-Soft** [comment]
Should be fixed with 1.50 RC1.
