### ISSUE TITLE
Landscape orientation and Letter format missing footer.

### ISSUE THREAD

**Issue by brunis** [empira/PDFsharp-1.5#116]
If you think there is a bug in PDFsharp then please use the IssueSubmissionTemplate to make the issue replicable.  
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

Thanks.

# Resources

The official project web site:  
http://pdfsharp.net/

The official peer-to-peer support forum:  
http://forum.pdfsharp.net/

# Reporting an Issue Here
## Expected Behavior

Footer should be attached to all pages regardless of orientation or page format.

## Actual Behavior

Footer is missing from Landscape orientation and Letter format

## Steps to Reproduce the Behavior
We strongly recommend using the IssueSubmissionTemplate to make sure we can replicate the issue.  
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

**Comment by ThomasHoevel** [comment]
PDFsharp does not support footers. MigraDoc supports footers.

Closed as "cannot reproduce".
