### ISSUE TITLE
New PdfDocument defaults to version 1.0 and PdfReader.Open() fails to open it

### ISSUE THREAD

**Issue by AGlezB** [empira/PDFsharp-1.5#121]
PDFsharp: 1.50.5147

If you create a new PDF using `new PdfDocument()`, save it and try to open it with `PdfReader.Open()` it fails with `File is not a valid PDF `file`.`

Looking at the document properties I noticed this:
![image](https://user-images.githubusercontent.com/12277525/77483512-14bd5400-6e07-11ea-8af0-f25d6ec88727.png)

`PdfReader.Open()` works fine ffter setting `pdf.Version = 14`. I didn't try other versions.

This is only a bug because PDFSharp cannot open the files created with the default settings.
Please consider changing the default version to something `PdfReader.Open()` can handle.

**Comment by ThomasHoevel** [comment]
Did you add any pages?
Please try the PDF created by the Hello World sample.
See also:
http://pdfsharp.net/wiki/IssueSubmissions.ashx
http://pdfsharp.net/wiki/HelloWorld-sample.ashx

**Comment by AGlezB** [comment]
We have a WinForms app that uses SSRS to generate a bunch of PDF reports then PDFSharp to merge those in a single PDF file. Then our client requested to merge some of those previusly merged files to email their clients a single file. 

For exalmple the app creates a bunch of individual reports for 2019, say Billing, Expenses, Raw Material usage, Production, etc. for single client and then merges those in a single PDF like {ClientID}_{Yeay}.pdf.
Then our client says they want 2019 and 2018 in a single file, so we grab the existing files and merge them before sending them to their client and here we failed to merge {ClientID}_2018.pdf and {ClientID}_2019.pdf because of the issue with the version.

Unfortunately I cannot provide the code or a PDF sample since everything is covered in NDAs and whatnot. 

EDIT: Ok, this sould be safe
![image](https://user-images.githubusercontent.com/12277525/77539714-94d3d000-6e80-11ea-9f66-2d97915a569e.png)
That is a partial screenshot of Foxit Reader's file poperties.
That one fails to open with `PdfReader.Open()`

This one was generated with the same code but with one additional LOC setting version to 1.4
![image](https://user-images.githubusercontent.com/12277525/77539958-03b12900-6e81-11ea-8a37-f57c22dfb03a.png)
`PdfReader.Open()` has no issue with it.

**Comment by AGlezB** [comment]
This should also be safe
![image](https://user-images.githubusercontent.com/12277525/77541371-5986d080-6e83-11ea-928f-bf05c2ba6b38.png)

![image](https://user-images.githubusercontent.com/12277525/77541529-8cc95f80-6e83-11ea-8303-340e25d75904.png)
