### ISSUE TITLE
[Bug] page break with PDFSharp

### ISSUE THREAD

**Issue by lukas124** [empira/PDFsharp-1.5#122]
I try to convert XAML view to PDF using PdfSharp but everything works fine except page break. On some pages I have situation that part of some elements is hidden because I do not have enough space on the page. It is library bug. 
![K9oYP](https://user-images.githubusercontent.com/1086052/78760093-ef8d2180-7980-11ea-959b-d33be02fad68.png)

**Comment by ThomasHoevel** [comment]
No source code provided. Unclear which library is used. Probably not a bug of the PDFsharp library.
