### ISSUE TITLE
Asynchronous Function Calls

### ISSUE THREAD

**Issue by bradlis7** [empira/PDFsharp-1.5#131]
## Expected Behavior

When accessing files, Asynchronous programming should be used.

Add method calls for any applicable methods, including

```
Task<PdfDocument> OpenAsync(...);
Task SaveAsync(...);
```

## Actual Behavior

Only synchronous methods available.

**Comment by ThomasHoevel** [comment]
This will not come soon.

It is recommend to use a separate thread for PDF generation while using the current API if responsiveness is an issue.
