### ISSUE TITLE
Sample projects no longer available for download

### ISSUE THREAD

**Issue by MegaMech** [empira/PDFsharp-1.5#134]
Please update the wiki links to go to the github to download samples. I couldn't find the samples.

Can someone send me the "Preview" sample. It's not in the samples github.
http://pdfsharp.net/wiki/Preview-sample.ashx
Thanks.

**Comment by TH-Soft** [comment]
The samples still are in the samples github.
https://github.com/empira/PDFsharp-samples

https://github.com/empira/PDFsharp-samples/tree/master/samples/gdi/GraphicsPreview
