### ISSUE TITLE
Question: Is it compatible with .NET 5.0?

### ISSUE THREAD

**Issue by osamakawish** [empira/PDFsharp-1.5#136]
More of a question and I'm not sure the best place to ask. Have yet to get to the point where I need to make actual PDF files, but as the title says, is it compatible with .NET 5.0? And if not, are there any plans to make a .NET 5.0 version?

I ask because at the moment, I get a warning saying that it's not intended for .NET 5.0 and there may be bugs.

**Comment by hangy** [comment]
Probably the same as #6 and #66? 🙂

**Comment by ThomasHoevel** [comment]
As of PDFsharp 6.0.0, PDFsharp is now using .NET 6.
