### ISSUE TITLE
Project is MIT Licensed but SharpZipLib files have GPL license comments

### ISSUE THREAD

**Issue by mhohimer** [empira/PDFsharp-1.5#140]
I'd like to use this library in a commercial capacity without modification, but am concerned that the presence of GPLv2 licenses in the SharpZipLib directory may annul the MIT license of this project.

For example: https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/SharpZipLib/SharpZipBaseException.cs

Can anyone provide clarity on this issue? If this is a license violation (I am not trying to imply it is; I'm not a lawyer), then maybe it would be possible to replace the SharpZipLib directory with a MIT-licensed version of SharpZipLib, e.g. https://github.com/icsharpcode/SharpZipLib

**Comment by Kingdom-Of-Heaven** [comment]
So is it really free for commercial use?

**Comment by TH-Soft** [comment]
IANAL but IMHO the "special exception" in lines 24 through 34 in the linked file allows bundling SharpZipLib with modules licensed under MIT license.

**Comment by Kingdom-Of-Heaven** [comment]
Would be nice to know that for sure.. :/ P.S Could you  give me that link?

**Comment by ThomasHoevel** [comment]
> Could you give me that link?

Click on the blue text in the first post after "For example".

**Comment by Kingdom-Of-Heaven** [comment]
I see. Hmm so "seems" like using pdfsharp whom contains SharpZipLib still can be used in commercial usage even with sell option.

**Comment by Kingdom-Of-Heaven** [comment]
From the other hand and to be honest for me marking software under MIT means it's MIT. I mean this software owner should knows whether it's still MIT or not once used inside.

**Comment by ThomasHoevel** [comment]
Now we have preview 1 of PDFsharp 6.0.0 where SharpZipLib code is no longer used.
