### ISSUE TITLE
sample code for viewing PDF in winform and saving edits done

### ISSUE THREAD

**Issue by kunz398** [empira/PDFsharp-1.5#148]
i would like to know how to view PDF in winform and save the edits done.

**Comment by ThomasHoevel** [comment]
Use a PDF viewer or a PDF editor.

**Comment by kunz398** [comment]
does pdf sharp provide that?

**Comment by ThomasHoevel** [comment]
No. Guess why this is labelled "off topic".
http://pdfsharp.net/wiki/PDFsharpFAQ.ashx
