### ISSUE TITLE
Invalid entry in XRef table

### ISSUE THREAD

**Issue by bagsergen** [empira/PDFsharp-1.5#154]
# Resources
[sample-pdf-with-images.pdf](https://github.com/empira/PDFsharp/files/7787945/sample-pdf-with-images.pdf)

# Issue
Hi, I'm trying to add info element. Error as below has occured when I tried this case. Sample file is downloaded from internet.

Environtment:
.Net 4.8 Framework

## Expected Behavior
The key-value should be added correctly.

## Actual Behavior
![Invalid entry](https://user-images.githubusercontent.com/53207601/147644557-81689053-e98e-4cb9-b61a-f3ee62684b86.PNG)

## Steps to Reproduce the Behavior

            PdfDocument document;
            try
            {
                document = PdfReader.Open(filePath);
                var properties = document.Info.Elements;                
                properties.SetString("/" + key, value);
                document.Save(filePath);
                document = null;                
                return true;
            }
            catch (Exception e)
            {
                if (document != null)
                    document = null;
                throw;
            }

**Comment by TH-Soft** [comment]
At first glance, this is a corrupt PDF file and not a bug in PDFsharp.

**Comment by bagsergen** [comment]
I understood, thank you.
