### ISSUE TITLE
The file is not a valid PDF Document (PDF 2.0)

### ISSUE THREAD

**Issue by bagsergen** [empira/PDFsharp-1.5#155]
# Resources
   [Simple_pdf_2.0_file.pdf](https://github.com/empira/PDFsharp/files/7788405/Simple_pdf_2.0_file.pdf)

# Issue
   Hi, I'm getting this error when I try to add info element on PDF 2.0. My purpose is custom metadata editing on pdf. Is PDFSharp supporting PDF 2.0 ? If not, can you suggest another package ?

   Environtment:
   .Net 4.8 Framework

## Expected Behavior
PdfSharp should open the file and add info element succesfully. 

## Actual Behavior
![pdf_v2-0_not_opened](https://user-images.githubusercontent.com/53207601/147653913-1771a451-c44e-471e-9851-bf3571ac4006.PNG)

## Steps to Reproduce the Behavior
        PdfDocument document;
        try
        {
            document = PdfReader.Open(filePath);
            var properties = document.Info.Elements;                
            properties.SetString("/" + key, value);
            document.Save(filePath);
            document = null;                
            return true;
        }
        catch (Exception e)
        {
            if (document != null)
                document = null;
            throw;
        }

**Comment by ThomasHoevel** [comment]
PDFsharp does not yet support PDF 2.0.

**Comment by ThomasHoevel** [comment]
PDFsharp 6.0.0 should now support PDF 2.0.
