### ISSUE TITLE
English resources missing in NuGet package

### ISSUE THREAD

**Issue by curia-damiano** [empira/PDFsharp-1.5#164]
# Issue
I can see from this GitHub repo that resources are available in English (default language) and German.
But in the resulting package, only the DE resources are available.

# Actual Behavior
But in the resulting package, only the DE resources are available.

# Steps to Reproduce the Behavior
You can verify opening the NuGet package or checking on NuGet.org

# Expected behavior
I would expect to see the resources even for the English language.

**Comment by ThomasHoevel** [comment]
The default resources are included in the main DLLs, the German resources come in separate files.
Nothing missing, all is there, English messages are showing.

You should expect to see English messages, but you cannot expect to see an EN folder with resources.

**Comment by curia-damiano** [comment]
I have found in the projects this:

<EmbeddedResource Include="Resources\Messages.de.restext">
<Generator>ResGen</Generator>
</EmbeddedResource>
<EmbeddedResource Include="Resources\Messages.restext" />

I wanted to submit a PR fixing the tool generator, but even after setting the generator tool to ResGen, the resource dlls are generated only in German...

**Comment by curia-damiano** [comment]
Thank you.
I am asking because I am embedding this NuGet package in a UWP app and there I get PRI236 warnings, saying that resources in the default language are missing...
