### ISSUE TITLE
pdf fails to open

### ISSUE THREAD

**Issue by KlaskSkovby** [empira/PDFsharp-1.5#166]
i have a pdf which fails to open with pdfSharp. the pdf file is 448 KB

i have located it to that the Symbol is an Integer instead of an Xref.

![image](https://user-images.githubusercontent.com/33638395/166413459-cdf3c5d2-1a19-4944-be18-8e1ef310e3e5.png)

then in the ReadXRefStream function it goes into the "Hack"

![image](https://user-images.githubusercontent.com/33638395/166413496-ef48f3d0-51e2-409d-90d5-f3f8ad259719.png)

and in the DecodeCrossReferenceStream function it throws the exception Invalid perdictor in array
![image](https://user-images.githubusercontent.com/33638395/166413538-d0f08957-907d-46a9-a224-adba400b697b.png)

How do i fix this?

![image](https://user-images.githubusercontent.com/33638395/166413556-47611e93-8009-4e37-b8b2-8b36308f78aa.png)

Can this be the issue?
https://www.verypdf.com/document/pdf-format-reference/pg_0093.htm
For a file that has never been updated, the cross-reference section contains only one subsection, whose object numbering begins at 0

**Comment by ThomasHoevel** [comment]
No file provided, not repro.
