### ISSUE TITLE
Font must use GraphicsUnit.World

### ISSUE THREAD

**Issue by chris-steema** [empira/PDFsharp-1.5#169]
## Expected Behavior

I've modified the [PdfSharpIssueSurrogate](https://github.com/LokiMidgard/PdfSharpIssueSurrogate) on a fork on my account [here](https://github.com/chris-steema/PdfSharpIssueSurrogate). This uses the [Jiyu No Tsubasa](https://www.freejapanesefont.com/jiyu-no-tsubasa-shingeki-nokyojin-font-download/) font, which is a TrueType font ([JiyunoTsubasa.ttf](https://github.com/chris-steema/PdfSharpIssueSurrogate/blob/master/PdfSharpIssueSurrogate/Resources/JiyunoTsubasa.ttf)). As per the PDFsharp documentation [here](http://pdfsharp.net/wiki/PostScript_fonts.ashx?AspxAutoDetectCookieSupport=1), I would expect this font to be used correctly.

## Actual Behavior

The code throws the following error:

```
System.ArgumentException
  HResult=0x80070057
  Message=Font must use GraphicsUnit.World.
  Source=PdfSharp
  StackTrace:
   at PdfSharp.Drawing.XFont..ctor(Font font, XPdfFontOptions pdfOptions)
   at PdfSharpIssueSurrogate.Program.Main(String[] args) in C:\Users\Chris\source\repos\PdfSharpIssueSurrogate\PdfSharpIssueSurrogate\Program.cs:line 25
```
And this error is thrown whichever values I choose for PdfFontEncoding and PdfFontEmbedding.

## Steps to Reproduce the Behavior

Please use the code above as specified.

**Comment by ThomasHoevel** [comment]
The font can be loaded using the IFontResolver interface.
Tested with EZFontResolver.
http://developer.th-soft.com/developer/2015/12/11/ezfontresolver-a-generic-font-resolver-for-pdfsharp-and-migradoc/

**Comment by ThomasHoevel** [comment]
In your code you are using these two lines where the error occurs:
`var font0 = new Font(privateFonts.Families[0], 20, FontStyle.Bold);`
`XFont font = new XFont(font0, new XPdfFontOptions(PdfFontEncoding.Unicode, PdfFontEmbedding.Default));`

The error does not occur when you skip the Font object and create the XFont object directly:
`XFont font = new XFont((FontFamily)privateFonts.Families[0], 20, XFontStyle.Bold);`

The XFontOptions can also be specified here:
`XFont font = new XFont((FontFamily)privateFonts.Families[0], 20, XFontStyle.Bold, new XPdfFontOptions(PdfFontEncoding.Unicode, PdfFontEmbedding.Default));`

**Comment by ThomasHoevel** [comment]
This is by design: Creating an `XFont` from `Font` works only when the font uses world co-ordinates.  
Creating the `XFont` directly from the font name is an easy solution for installed fonts.  
Implementing `IFontResolver` is another option.
