### ISSUE TITLE
Wrong order of arguments in Exceptions and other checks

### ISSUE THREAD

**Issue by jnyrup** [empira/PDFsharp-1.5#17]
Please have a look at this commit for places where the order of arguments for `ArgumentException` are switched, places where a variable used before a null check and use of the wrong variable in `Equals` method.
https://github.com/jnyrup/PDFsharp/commit/7d219d2b38152a6be6b8d19d43d7cc38d25942bc

**Comment by TH-Soft** [comment]
Thanks for the feedback, fixes will be included in the next release.
