### ISSUE TITLE
Using PDF Sharp in a .NET project

### ISSUE THREAD

**Issue by hajerkr** [empira/PDFsharp-1.5#174]
Hello,

This is not an issue, but more of an inquiry.
I downloaded PDF Sharp using the Nuget package on VS Studio- my understanding is that I can only use that for 30 days during the trial period. As of now it comes up with the watermark and / or the banner at the bottom with the tool link etc.

Is the version on this repo functional like the version available as a Nuget package? Any documentation as to how to use this in a .NET project?
Many thanks

**Comment by ThomasHoevel** [comment]
Are you sure you downloaded official NuGet packages from PDFsharp-Team? Those do not have watermarks and there is no trial period. The official PDFsharp is fully functional and published under MIT license.

https://www.nuget.org/profiles/PDFsharp-Team
