### ISSUE TITLE
Unexpected token 'eÐóù' in PDF stream. The file may be corrupted. If you think this is a bug in PDFsharp, please send us your PDF file

### ISSUE THREAD

**Issue by Arun1989ninja** [empira/PDFsharp-1.5#175]
If you think there is a bug in PDFsharp then please use the IssueSubmissionTemplate to make the issue replicable.  
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

Thanks.

# Resources

The official project web site:  
http://pdfsharp.net/

The official peer-to-peer support forum:  
http://forum.pdfsharp.net/

# Reporting an Issue Here
## Steps to Reproduce the Behavior
We strongly recommend using the IssueSubmissionTemplate to make sure we can replicate the issue.  
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

**Comment by TH-Soft** [comment]
Corrupt files are corrupt files.

**Comment by ThomasHoevel** [comment]
No file provided, not repro.
