### ISSUE TITLE
PDFsharp watermark can be remove!!!

### ISSUE THREAD

**Issue by mustafaxoodiye** [empira/PDFsharp-1.5#176]
When the watermark is added to a pdf and saved successfully. If you convert that pdf file to a word using any conversions tool like "https://www.ilovepdf.com/pdf_to_word".

The watermark can be removed when opened in word.

Is there any way to make the pdf with the watermark stick together like one image??

**Comment by TH-Soft** [comment]
The best you can try is setting an owner password. But this will not stop all tools from manipulating the file.

**Comment by mustafaxoodiye** [comment]
Thanks, It worked with setting the owner's password. However, as you mentioned, this won't stop all tools from cracking it.
Therefore, does your library provide pdf to HTML conversion?

**Comment by ThomasHoevel** [comment]
PDFsharp cannot render PDF in any form, including HTML.
