### ISSUE TITLE
Images and encryption break the resulting document

### ISSUE THREAD

**Issue by highfield** [empira/PDFsharp-1.5#19]
The issue is pretty simple to reproduce: add an image and set the encryption of the document. The result is a broken document (Adobe Reader alerts that), and not image displayed. Other objects seem rendering fine, though.

What I found is about a double-RC4 encryption (thus no encryption) on stream objects. Removing one of them, the resulting document seems okay.

The first encryption is performed here: https://github.com/empira/PDFsharp/blob/b84018e1ef6c646a4062c7bb4f53561c4027d48f/src/PdfSharp/Pdf.Security/PdfStandardSecurityHandler.cs#L170

The second one here, during the document saving (Save method to file): https://github.com/empira/PDFsharp/blob/b84018e1ef6c646a4062c7bb4f53561c4027d48f/src/PdfSharp/Pdf.IO/PdfWriter.cs#L428

At this point, the question is: which one is the better to remove?

**Comment by highfield** [comment]
It seems that you must comment out the encryption call in the security handler module. By trying to comment out in the writer, the document becomes totally broken...

**Comment by TH-Soft** [comment]
Should be fixed.
