### ISSUE TITLE
Use the "CodePagesEncodingProvider" where codepages are not supported

### ISSUE THREAD

**Issue by highfield** [empira/PDFsharp-1.5#21]
If you try to map the sources for .Net Core (.Net Standard 2.0), you'll face an exception when an external OpenType font is loaded.

The exception is a "NotSupportedException", and it's thrown by the Encoding.GetEncoding(1252) call. The reason is well explained [here](https://msdn.microsoft.com/en-us/library/system.text.codepagesencodingprovider(v=vs.110).aspx).
```
namespace PdfSharp.Pdf.Internal
{
    /// <summary>
    /// Groups a set of static encoding helper functions.
    /// </summary>
    internal static class PdfEncoders
    {
        ...

        /// <summary>
        /// Gets the Windows 1252 (ANSI) encoding.
        /// </summary>
        public static Encoding WinAnsiEncoding
        {
            get
            {
                if (_winAnsiEncoding == null)
                {
#if !SILVERLIGHT && !NETFX_CORE && !UWP
                    // Use .net encoder if available.
                    _winAnsiEncoding = CodePagesEncodingProvider.Instance.GetEncoding(1252);
                    //_winAnsiEncoding = Encoding.GetEncoding(1252);
#else
                    // Use own implementation in Silverlight and WinRT
                    _winAnsiEncoding = new AnsiEncoding();
#endif
                }
                return _winAnsiEncoding;
            }
        }

        ...
    }
}
```
By following the suggestion [here](https://stackoverflow.com/questions/37870084/net-core-doesnt-know-about-windows-1252-how-to-fix), the problem seems solved.

However, I believe it should be made active via a proper conditional switch.

**Comment by zmmille2** [comment]
Fairly certain I'm running into this issue.  Is there something I can do locally in my project to enable `pdfDocument.Save(ms)` to work with OpenType fonts?  Can I load the encoder, or would I have to do this in the library?

**Comment by shashi4u** [comment]
**Solution 1:**

Add package **System.Text.Encoding.CodePages** to your project and call **Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);** before you create/save pdf document.


**Solution 2:**

Add **!NETSTANDARD** to the if condition to the above code @highfield has mentioned.

The final **#if** condition would be

**#if !SILVERLIGHT && !NETFX_CORE && !UWP && !NETSTANDARD**
