### ISSUE TITLE
Support for "ImageSharp"

### ISSUE THREAD

**Issue by highfield** [empira/PDFsharp-1.5#22]
For cross-platform applications (i.e. .Net Core 2.0) I'd suggest to add the support for [ImageSharp](https://github.com/SixLabors/ImageSharp) as graphics interface.

I've been able to make it working, but that was because [someone else](https://github.com/groege/PdfSharpCore) made it work before me!

The current mine is somewhat meant as temporary until a better implementation will be available. Let me know if you're interested in my attempt.

**Comment by flensrocker** [comment]
There's now a .Net Core 2 replacement for System.Drawing by Microsoft:
https://www.nuget.org/packages/System.Drawing.Common/

**Comment by andymac4182** [comment]
@flensrocker That is only supported on Windows from my understanding as it is still based on GDI

**Comment by flensrocker** [comment]
Looking at [1] there is no "Windows Only" marker for System.Drawing.Common.

[1] https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/

**Comment by groege** [comment]
Afaik the best available libs to support are ImageSharp vs System.Drawing.Common vs SkiaSharp.
Maybe it should be possible to implement an interface which can be implemented for different platforms and implement one of the three as a default?

**Comment by TH-Soft** [comment]
@groege I'm not the software architect of this project and I do not decide what will be implemented. But there surely are several ways to implement different types of image handling for different platforms or different configurations.

**Comment by highfield** [comment]
@groege ImageSharp gains at least two points over System.Drawing: first off, it supports concurrency thus is the natural choice for server-side solutions. Secondly, seems way faster than the Microsoft way.

I didn't test SkiaSharp yet, but I typically prefer a full-managed library because the portability across OSes is much more reliable.

**Comment by fuzzzerd** [comment]
Looks like they're switching to a commercial license: https://sixlabors.com/blog/beta-six-labors/.

**Comment by shashi4u** [comment]
ImageSharp's license is AGPLv3. Is it compatible with PDFSharp's which is MIT?

EDIT:
I researched on license compatibility between MIT and AGPLv3 and found that you can use MIT licensed code inside AGPL licensed code and not other way around.
So,  ImageSharp due to its's license cannot be used with PDFSharp.

**Comment by shashi4u** [comment]
According to this [comment](https://stackoverflow.com/questions/40892189/net-core-and-system-drawing#comment93510719_51412644) you need to install **libgdiplus** in linux / macOS for System.Drawing to work on these platforms.

SkiaSharp & Magick.NET also seems to have runtime dependencies for different OS platforms.

**Comment by aeb-dev** [comment]
FYI: Currently, ImageSharp's license is Apache-2.0
https://github.com/SixLabors/ImageSharp/blob/master/LICENSE

**Comment by fuzzzerd** [comment]
It does seem that they back tracked a bit and their v1.0.x nuget packages are still Apache-2.0 licensed: https://www.nuget.org/packages/SixLabors.ImageSharp/1.0.3.

Building on a package that we know is likely to change to an incompatible license maybe isn't the best idea, but the ImageSharp betas were all quite solid. I expect the v1.0 branch to remain good enough for most uses, even if subsequent versions are not licensed as compatibly. So if their v1 covers the uses needed, maybe that's good enough.

**Comment by ThomasHoevel** [comment]
PDFsharp 6.0.0 uses a different approach. Feel free to use ImageSharp in your port of PDFsharp.
