### ISSUE TITLE
NullReferenceException in PdfReader.Open

### ISSUE THREAD

**Issue by jeff-wtg** [empira/PDFsharp-1.5#23]
Hi guys,
Currently I am suffering a null reference exception when calling the static function
PdfReader.Open(Stream stream, PdfDocumentOpenMode mode).

in my case the mode is **PdfDocumentOpenMode.Import**

Did you guys encounter this error before? And did I miss something?

Thanks.

**Comment by ThomasHoevel** [comment]
Make it reproducible.
See also:
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

**Comment by jeff-wtg** [comment]
Hi Thomas,

After debugging the source code, I figured out the reason why it threw null reference exception. 
Here is the stack traces:

>	PdfSharp.dll!PdfSharp.Pdf.IO.Parser.ReadXRefTableAndTrailer(PdfSharp.Pdf.Advanced.PdfCrossReferenceTable xrefTable) Line 1063	C#
 	PdfSharp.dll!PdfSharp.Pdf.IO.Parser.ReadTrailer() Line 1039	C#
 	PdfSharp.dll!PdfSharp.Pdf.IO.PdfReader.Open(System.IO.Stream stream, string password, PdfSharp.Pdf.IO.PdfDocumentOpenMode openmode, PdfSharp.Pdf.IO.PdfPasswordProvider passwordProvider) Line 300	C#
 	PdfSharp.dll!PdfSharp.Pdf.IO.PdfReader.Open(System.IO.Stream stream, string password, PdfSharp.Pdf.IO.PdfDocumentOpenMode openmode) Line 272	C#
 	PdfSharp.dll!PdfSharp.Pdf.IO.PdfReader.Open(System.IO.Stream stream, PdfSharp.Pdf.IO.PdfDocumentOpenMode openmode) Line 257	C#
 	ConsoleApp.exe!ConsoleApp.Program.Main(string[] args) Line 31	C#

in Parser.cs ReadTrailer() method (at line 1000)

![image](https://user-images.githubusercontent.com/31689851/30144426-b95c0f64-93bd-11e7-87fa-954fa9d23ffd.png)

my pdf file's length exceeds 1030, so getting the trail string like below:

![image](https://user-images.githubusercontent.com/31689851/30144464-faf97830-93bd-11e7-884b-7c70372ee69d.png)

However, the integer **928472**  below the StartXRef is refering to an endobj.

![image](https://user-images.githubusercontent.com/31689851/30144613-cef15662-93be-11e7-955d-724687a939d6.png)

so the method ReadXRefTableAndTrailer(PdfCrossReferenceTable xrefTable) returns null. 

![image](https://user-images.githubusercontent.com/31689851/30144646-0e703948-93bf-11e7-8b76-bbf5e124d1bd.png)

and then it would throw the null reference exception because the trailer is null. 

Hopefully this helps. 
Thanks.

**Comment by ThomasHoevel** [comment]
PDFsharp expects to find the start of the XREF table after the "startxref" entry. Adobe Reader does a good job with respect to repairing damaged/corrupted PDF files (analyzing the contents when the table of contents is wrong or missing).
Looks like "not a bug in PDFsharp, but a corrupted PDF file".
Thanks for you analysis. I'm afraid this case can be closed.
Over time PDFsharp will become better with respect to working around common corruption of PDF files, but scanning the whole file to rebuild the XREF table will not come in the foreseeable future.

**Comment by icymoonicy** [comment]
Hi Thomas,
Since we're unable rebuild the XREF table, could you please throw a more specific exception with accurate error message for this issue? To me a NRE exception here is too difficult for developers to handle. @ThomasHoevel

**Comment by ThomasHoevel** [comment]
@icymoonicy We do not throw an exception, a corrupted file leads to an NRE.
I'll discuss the idea of throwing specific exceptions for certain corruptions with my boss.

You try to open the PDF file, you get an exception from PdfReader.Open. NRE will lead to a "Contact us" message, an InvalidXrefTableException will lead to a "Contact the maker of the PDF file" message.
Beside that, what other advantages would a specific exception have?

**Comment by icymoonicy** [comment]
@ThomasHoevel I cannot come up with any other ideas so far. 
Thanks man!

**Comment by jeff-wtg** [comment]
@ThomasHoevel 
Thanks for your reply, and how about the result of discussion with your boss about throwing the specific exception :)

**Comment by TH-Soft** [comment]
Beginning with 1.50 RC2 (coming soon) a PdfReaderException should be thrown for such invalid files.
