### ISSUE TITLE
Reader.Open

### ISSUE THREAD

**Issue by tklee33** [empira/PDFsharp-1.5#25]
I get an "Object already in table issue", I've been able to manipulate a lot of Pdfs but all of a sudden this issue arose for a specific pdf.

It looks like, it thinks it's not done?

![image](https://user-images.githubusercontent.com/20565943/30342587-6308e434-97c8-11e7-93bc-8fb3c2aa3eda.png)

i'm assuming after the first loop, the variable "prev" is supposed to be zero? so it breaks out of the loop?
is there something specific i am supposed to look for in the pdf itself?

![image](https://user-images.githubusercontent.com/20565943/30342661-9cbfb4aa-97c8-11e7-801f-02680c3249a1.png)

**Comment by tklee33** [comment]
more information if it helps

![image](https://user-images.githubusercontent.com/20565943/30342848-4699657a-97c9-11e7-9491-6877165d36b1.png)

**Comment by ThomasHoevel** [comment]
Make the issue reproducible. See also:
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

**Comment by TH-Soft** [comment]
Not replicable without the PDF.
