### ISSUE TITLE
NullReferenceException when saving with owner password

### ISSUE THREAD

**Issue by RichardD2** [empira/PDFsharp-1.5#30]
## Steps to reproduce:
* Create a new console application;
* Add a NuGet reference: `Install-Package PDFsharp-gdi -Version 1.50.4619-beta4c`;
* Copy the code from the "Hello World" sample application;
* Set an owner password, a user password, or both before the call to `Save`;

## Expected result:
The document should be saved and protected with a password.

## Actual result:
```
System.NullReferenceException: Object reference not set to an instance of an object.
    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.PrepareRC4Key(Byte[] key, Int32 offset, Int32 length)
    at PdfSharp.Pdf.Internal.PdfEncoders.FormatStringLiteral(Byte[] bytes, Boolean unicode, Boolean prefix, Boolean hex, PdfStandardSecurityHandler securityHandler)
    at PdfSharp.Pdf.IO.PdfWriter.WriteDocString(String text)
    at PdfSharp.Pdf.PdfDate.WriteObject(PdfWriter writer)
    at PdfSharp.Pdf.PdfDictionary.WriteDictionaryElement(PdfWriter writer, PdfName key)
    at PdfSharp.Pdf.PdfDictionary.WriteObject(PdfWriter writer)
    at PdfSharp.Pdf.PdfDocument.DoSave(PdfWriter writer)
    at PdfSharp.Pdf.PdfDocument.Save(Stream stream, Boolean closeStream)
    at PdfSharp.Pdf.PdfDocument.Save(String path)
```

## Code:
```c#
static void Main()
{
    // Create a new PDF document
    PdfDocument document = new PdfDocument();
    document.Info.Title = "Created with PDFsharp";

    // Create an empty page
    PdfPage page = document.AddPage();

    // Get an XGraphics object for drawing
    XGraphics gfx = XGraphics.FromPdfPage(page);

    // Create a font
    XFont font = new XFont("Times New Roman", 20, XFontStyle.BoldItalic);

    // Draw the text
    gfx.DrawString("Hello, World!", font, XBrushes.Black,
        new XRect(0, 0, page.Width, page.Height),
        XStringFormats.Center);

    // Set the password(s):
    document.SecuritySettings.OwnerPassword = "password";
    document.SecuritySettings.UserPassword = "password";

    // Save the document...
    const string filename = "HelloWorld_tempfile.pdf";
    document.Save(filename);

    // ...and start a viewer.
    Process.Start(filename);
}
```

### Notes:
* It doesn't matter whether you set the owner password, the user password, or both.
* It doesn't matter *what* you set the password to, so long as it's not an empty string.
* It doesn't matter whether you're creating a new document, or modifying an existing document.

### System details:
* Microsoft Visual Studio Professional 2017 version 15.4.2
* Microsoft .NET Framework version 4.7.02556
* Windows 10 v1709 build 16299.19

**Comment by RichardD2** [comment]
Same issue as #31:
* `PdfEncoders.FormatStringLiteral` 
* calls `PdfStandardSecurityHandler.EncryptBytes(byte[])`, 
* calls `PrepareKey()`, 
* calls `PrepareRC4Key(byte[], int, int)`, passing in the uninitialized `_key` field.

**Comment by TH-Soft** [comment]
Not replicable with RC1.
