### ISSUE TITLE
NullReferenceException when opening a PDF/A Document

### ISSUE THREAD

**Issue by Enceradeira** [empira/PDFsharp-1.5#31]
When opening a PDF/A-Document with the following code I get a NullReferenceException:

```           
PdfReader.Open(pdfFileName, PdfDocumentOpenMode.ReadOnly));
```

> The exception is:
> System.NullReferenceException : Object reference not set to an instance of an object.
>    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.PrepareRC4Key(Byte[] key, Int32 offset, Int32 length)
>    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.PrepareKey()
>    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.EncryptString(PdfString value)
>    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.EncryptDictionary(PdfDictionary dict)
>    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.EncryptArray(PdfArray array)
>    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.EncryptDictionary(PdfDictionary dict)
>    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.EncryptObject(PdfObject value)
>    at PdfSharp.Pdf.Security.PdfStandardSecurityHandler.EncryptDocument()
>    at PdfSharp.Pdf.IO.PdfReader.Open(Stream stream, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider passwordProvider)
>    at PdfSharp.Pdf.IO.PdfReader.Open(String path, String password, PdfDocumentOpenMode openmode, PdfPasswordProvider provider)
>    at PdfSharp.Pdf.IO.PdfReader.Open(String path, PdfDocumentOpenMode openmode)
>    at Garaio.REM.Business.Printing.PdfAppenderFixture.PageCountOf(String pdfFileName) in C:\projects\garaio\REM\04_Development\Garaio.REM.REWE.Tester\Garaio.REM.Business\Printing\PdfAppenderFixture.cs:line 29

**Comment by Enceradeira** [comment]
Please find code that reproduces the issue in the attachment: [PDFsharp-IssueSubmission #31.zip](https://github.com/empira/PDFsharp/files/1445771/PDFsharp-IssueSubmission.31.zip). Please see IssueSubmission-core/Program.cs

**Comment by RichardD2** [comment]
Could be related to #30 - it's the same exception in the same method, just a different way of triggering it.

**Comment by ThomasHoevel** [comment]
Thanks for the IssueSubmission ZIP. Exception occurs with beta 4c, but not with beta 4. Issue requires further investigation, but not today (or at least not from me).

**Comment by RichardD2** [comment]
Using dotPeek, it looks like this problem is due to the fact that the `_key` field is never assigned.

```c#
private byte[] _key;

private void PrepareKey()
{
    PrepareRC4Key(_key, 0, _keySize);
}

private void PrepareRC4Key(byte[] key, int offset, int length)
{
    int num1 = 0;
    int index1 = 0;
    for (int index2 = 0; index2 < 256; ++index2)
    {
        _state[index2] = (byte) index2;
    }
    for (int index2 = 0; index2 < 256; ++index2)
    {
        index1 = (int) key[num1 + offset] // <-- BOOM!
            + (int) this._state[index2] 
            + index1 & (int) byte.MaxValue;
        
        byte num2 = this._state[index2];
        this._state[index2] = this._state[index1];
        this._state[index1] = num2;
        num1 = (num1 + 1) % length;
    }
}
```

`PrepareKey()` is the only place the `_key` field is used.

**Comment by ThomasHoevel** [comment]
_key was not assigned with beta 4, _key is not assigned with beta 4c. Still beta 4 did not crash, but beta 4c does.
Experimental change: Added "if (_key != null && _keySize > 0)" in "PrepareKey()".
It could be that "PrepareKey()" is obsolete, but I'm afraid I do not understand enough of that code yet to be sure about that.

**Comment by RichardD2** [comment]
In the version in this repo, the `_key` field is initialized in the `SetHashKey` method, inside an `#if !NETFX_CORE` conditional:

https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/Pdf.Security/PdfStandardSecurityHandler.cs#L528

```C#
        internal void SetHashKey(PdfObjectID id)
        {
#if !NETFX_CORE
            //#if !SILVERLIGHT
            byte[] objectId = new byte[5];
            _md5.Initialize();
            // Split the object number and generation
            objectId[0] = (byte)id.ObjectNumber;
            objectId[1] = (byte)(id.ObjectNumber >> 8);
            objectId[2] = (byte)(id.ObjectNumber >> 16);
            objectId[3] = (byte)id.GenerationNumber;
            objectId[4] = (byte)(id.GenerationNumber >> 8);
            _md5.TransformBlock(_encryptionKey, 0, _encryptionKey.Length, _encryptionKey, 0);
            _md5.TransformFinalBlock(objectId, 0, objectId.Length);
            _key = _md5.Hash;
            _md5.Initialize();
            _keySize = _encryptionKey.Length + 5;
            if (_keySize > 16)
                _keySize = 16;
            //#endif
#endif
        }
```

In the beta 4c version from NuGet, that method seems to be empty:
![image](https://user-images.githubusercontent.com/2158265/32452238-e115fe2a-c310-11e7-8dee-360a6101b30b.png)

Has someone toggled the `NETFX_CORE` switch on the non-Core projects?

**Comment by TH-Soft** [comment]
The issue cannot be replicated with 1.50 RC1.
