### ISSUE TITLE
PDFSharp losing annotations

### ISSUE THREAD

**Issue by mk67** [empira/PDFsharp-1.5#38]
Hi there, 
this bug is still active!

https://stackoverflow.com/questions/38733190/pdfsharp-losing-annotations

Best regards,
Maurice

**Comment by ThomasHoevel** [comment]
Fixed with the latest internal builds. Fix is documented in the forum.

**Comment by mk67** [comment]
Where can I find this internal build or when is the next beta planned?
Or otherwise can you please send me a link to the forum - I can't find the solution!

Many thanks in advance!

Best regards,
Maurice

**Comment by ThomasHoevel** [comment]
Link to the fix on the forum:  
http://forum.pdfsharp.net/viewtopic.php?p=11196#p11196

There is no ETA for the next beta.

**Comment by mk67** [comment]
Many thanks!
