### ISSUE TITLE
Square brackets "[]" in custom property name corrupts pdf file on save

### ISSUE THREAD

**Issue by ehcanadianCA** [empira/PDFsharp-1.5#43]
If a PDF has a custom property whose name contains square brackets the file is corrupted when it is saved by PDFsharp. On the next open, PDFsharp gives an UnexpectedToken error and is unable to open the file. One is able to open the file in Acrobat Reader, but not able to view the file's properties.

I have included an example solution.
[CustomPropertyIssue.zip](https://github.com/empira/PDFsharp/files/1639959/CustomPropertyIssue.zip)

**Comment by ThomasHoevel** [comment]
Not replicable. The file opens using beta5 without throwing an exception.

**Comment by ehcanadianCA** [comment]
The PDF isn't corrupt until PDFsharp saves it. The exception occurs on line 39 of the example I submitted. I just tested with beta5 and the issue exists.

In this case, the PDF has a custom property of 'Nominal Diameter [in]'.

![image](https://user-images.githubusercontent.com/8474633/35102343-ae7bac90-fc30-11e7-8ec0-149387f4bb1b.png)

**Comment by ehcanadianCA** [comment]
Attached is an updated solution. It opens the PDF that has the custom property in it and saves it to a new file. That file causes an exception on load. I then delete the custom property and save the file again. That new file opens fine.
[CustomPropertyIssueBeta5.zip](https://github.com/empira/PDFsharp/files/1643169/CustomPropertyIssueBeta5.zip)

**Comment by ThomasHoevel** [comment]
I see the problem now. Under investigation ...

**Comment by ThomasHoevel** [comment]
Quick fix: in file PdfWriter.cs locate the method "public void Write(PdfName value)" and insert two new lines for square brackets:
case ')':
case '[':
case ']':
case '#':

This change will be included with the next release.

**Comment by ehcanadianCA** [comment]
Excellent, thank you!
