### ISSUE TITLE
Cant build source code

### ISSUE THREAD

**Issue by uzair08inator** [empira/PDFsharp-1.5#44]
I downloaded the PDF Sharp source code from Sourceforge. When i open the solution 'BuildAll-PdfSharp.sln' in VisualStudio and try to build, i am getting following build errors 

Error	14	Metadata file 'D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp-gdi\bin\Debug\PdfSharp-gdi.dll' could not be found	D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp.Charting-gdi\CSC	PdfSharp.Charting-gdi
Error	15	Metadata file 'D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp-wpf\bin\Debug\PdfSharp-wpf.dll' could not be found	D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp.Charting-wpf\CSC	PdfSharp.Charting-wpf
Error	13	Metadata file 'D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\bin\Debug\PdfSharp.dll' could not be found	D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp.Charting\CSC	PdfSharp.Charting
Error	1	The name 'nameof' does not exist in the current context	D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Advanced\PdfPageInheritableObjects.cs	67	88	PDFsharp
Error	2	The name 'nameof' does not exist in the current context	D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Drawing\XUnit.cs	71	78	PDFsharp
Error	3	The name 'nameof' does not exist in the current context	D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Advanced\PdfContents.cs	131	49	PDFsharp
Error	4	The name 'nameof' does not exist in the current context	D:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Content.Objects\CObjects.cs	775	53	PDFsharp
Error	5	The name 'nameof' does not exist in the current context	d:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Advanced\PdfPageInheritableObjects.cs	67	88	PdfSharp-gdi
Error	6	The name 'nameof' does not exist in the current context	d:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Drawing\XUnit.cs	71	78	PdfSharp-gdi
Error	7	The name 'nameof' does not exist in the current context	d:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Advanced\PdfContents.cs	131	49	PdfSharp-gdi
Error	8	The name 'nameof' does not exist in the current context	d:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Content.Objects\CObjects.cs	775	53	PdfSharp-gdi
Error	9	The name 'nameof' does not exist in the current context	d:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Advanced\PdfPageInheritableObjects.cs	67	88	PdfSharp-wpf
Error	10	The name 'nameof' does not exist in the current context	d:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Drawing\XUnit.cs	71	78	PdfSharp-wpf
Error	11	The name 'nameof' does not exist in the current context	d:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Advanced\PdfContents.cs	131	49	PdfSharp-wpf
Error	12	The name 'nameof' does not exist in the current context	d:\eProof\testProjects\PDFSharp_Github\PDFsharp\src\PdfSharp\Pdf.Content.Objects\CObjects.cs	775	53	PdfSharp-wpf

Can anyone help me out with building this?

**Comment by groege** [comment]
I don't know anything about BuildAll-PdfSharp.sln, use  PdfSharp.sln
<https://github.com/groege/PdfSharpCore/blob/master/PdfSharp.sln>

**Comment by ThomasHoevel** [comment]
"nameof" is a new C# feature, so maybe try VS 2017 Community Edition to build PDFsharp if you still use VS 2015 or older. Or replace 'nameof(foo)' with '"foo"'. Sorry for the inconvenience, but a few new C# features slipped into it.

**Comment by uzair08inator** [comment]
Thanks man. the issue was that i was trying to build in an older version of VS and 'nameof' is not supported. I replaced like u said and it build successfully.
