### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by damiankras** [empira/PDFsharp-1.5#45]
After some research and several clicks I found that:

On site https://archive.codeplex.com/?p=pdfsharp there is information that project was migrated to github
also on this page I found link to project page http://www.pdfsharp.net/ where I fonud that it is licensed under MIT 

Can license information as well as project homepage can be added to github README.md 
It will be more than helpful to have that information close to code

Benefits:
Github search filter will work better if we searching by license
Reduce number of clicks to find license information 
Will be much clearer under what license is this project for github users

**Comment by ThomasHoevel** [comment]
>

**Comment by ThomasHoevel** [comment]
> It will be more than helpful to have that information close to code
With source codes coming from different sources, we have different licenses with different authors across the project. We have the license as close to the code as possible.

**Comment by damiankras** [comment]
Yes sometime in source files we can see kind of license nottice.
But under what license whole PDFsharp project is conducted?
If under multiple licenses, maybe will be good to add such information in README.md
It is hard to find this for someone that visit github project page for first time
Also short summary of features will be appreciated in README file to get quick overview about project.

PS: There is one pull request with added license: https://github.com/empira/PDFsharp/pull/42
Take a look, it could be helpfull

**Comment by ThomasHoevel** [comment]
The pull request was known and was considered not helpful.
License file was now added.
