### ISSUE TITLE
Cannot add custom font

### ISSUE THREAD

**Issue by HoustonBill** [empira/PDFsharp-1.5#47]
When I try to add a custom font using PDFSharp.Drawing.XPrivateFontCollection.AddFont(), I get a warning that says the method is deprecated, and I should use Add(). There is no Add method. When I run it I get an exception.

I downloaded the code, and I can see in the XPrivateFontCollection.AddFont() method where the first line throws an exception. I also see the Add() method, but it is commented out.

I see you have just put RC1 out. It would be great if custom font support would work in the next release.

**Comment by TH-Soft** [comment]
Please use the IssueSubmissionTemplate to create an MCVE so we can replicate the issue and know which build of PDFsharp we are talking about.  
http://pdfsharp.net/wiki/IssueSubmissions.ashx

I'd recommend using the WPF build and the IFontResolver if possible.

**Comment by TH-Soft** [comment]
The method `public static void Add(Stream stream)` is available with the GDI build only. You are using either the Core build or the WPF build which do not have this method.  
You can also use `public static void Add(byte[] font)`.

**Comment by TH-Soft** [comment]
For those who think that implementing `IFontResolver` is a bit complicated, please allow me to advertise my `EZFontResolver` class that implements `IFontResolver` and makes standard font handling much easier.  
http://developer.th-soft.com/developer/2015/12/11/ezfontresolver-a-generic-font-resolver-for-pdfsharp-and-migradoc/
