### ISSUE TITLE
Feature: Export to string

### ISSUE THREAD

**Issue by ZTHawk** [empira/PDFsharp-1.5#48]
Hi,
I would like to see a feature to extract all text to string like PdfBox:
```
PDFTextStripper pdfTextStripper = new PDFTextStripper();
string contentOfAllPages = pdfTextStripper.getText(PDDocument.load(pdfFileName));
```

I have already found some code to generate content out of pages but the result has too many linebreaks. Espacially words are sometimes split across multiple lines.

**Comment by ThomasHoevel** [comment]
Extracting text from PDF is complicated and PDFsharp was not designed to extract text. There is third-party code that builds on PDFsharp to extract text.

There are code snippets on the PDFsharp forum.  
And there is this project:  
https://github.com/DavidS/PdfTextract
