### ISSUE TITLE
ContentReader.ReadContent(page) unicode issues

### ISSUE THREAD

**Issue by ZTHawk** [empira/PDFsharp-1.5#49]
Some characters are not correctly extracted (eg: unicode hyphen variant U+2013 == EN DASH == e2 80 93).
CString seems to be empty.

**Comment by ThomasHoevel** [comment]
If you think there is a bug in PDFsharp then please use the IssueSubmissionTemplate to make the issue replicable.  
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

Thanks.

**Comment by ZTHawk** [comment]
Here is the template. There is a console output what is expected, a concatenated string and each "Tj" item.
[pdfsharp_unicode_issue.zip](https://github.com/empira/PDFsharp/files/1829410/pdfsharp_unicode_issue.zip)

**Comment by ThomasHoevel** [comment]
Yes, your code does not extract the characters properly.
The PDF files contains <00B1> for the hyphen. The lookup table for the font gives the correct code <2013>. The "A" is coded as <0024> and the lookup table gives you <0041>.

As I understand it PDFsharp is working as expected. Decoding the content is up to you.

/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CIDSystemInfo
<< /Registry (Adobe)
/Ordering (UCS) /Supplement 0 >> def
/CMapName /Adobe-Identity-UCS def
/CMapType 2 def
1 begincodespacerange
<0000> <FFFF>
endcodespacerange
3 beginbfchar
<0003> <0020>
<0024> <0041>
<00B1> <2013>
endbfchar
endcmap CMapName currentdict /CMap defineresource pop end end

**Comment by cleversolutions** [comment]
@ThomasHoevel can you elaborate a bit more? For the test.pdf file @ZTHawk posted, how would someone decode the lookup table? I'm trying to extract text from PDFs using PDFSharp without having read the PDF spec.

**Comment by cleversolutions** [comment]
I assume what I need to do is build a dictionary for character replacement. The closest I can come so far to the lookup table is to grab ```page.Resources.Elements.GetDictionary("/Font").Elements.GetDictionary("/TT0").Elements.GetDictionary("/ToUnicode");``` but I haven't figured out what to do with the stream to build the dictionary. Am I going in the right direction, or is this information already parsed and waiting to be used somewhere else in the PdfSharp API? Thanks for any feedback you can provide.

**Comment by cleversolutions** [comment]
If anybody happens across this and are looking for an answer you can try this repo https://github.com/cleversolutions/pdfSharpTextExtrationTests. It's not 100% solution, but for the PDFs I've tested with it it seems to work well.
