### ISSUE TITLE
SharpZipBaseException on calling XGraphics.FromPdfPage

### ISSUE THREAD

**Issue by wbokkers** [empira/PDFsharp-1.5#5]
For a lot of PDF pages I get a SharpZipBaseException when calling XGraphics.FromPdfPage.
The exception is thrown in InflaterInputStream.Fill() with message "Unexpected EOF".

I can 'fix' this problem using a hack in InflaterInputStream.Read:

```
public override int Read(byte[] buffer, int offset, int count)

   ....
if (inf.IsNeedingInput)
{
    try
    {
        Fill();
    }
    catch(SharpZipBaseException)
    { // WB! early EOF: apparantly not a big deal for some PDF pages: break out of the loop.
        break; 
    }
}
     ...

```

**Comment by ThomasHoevel** [comment]
The hack was imported to the current internal build of PDFsharp.
