### ISSUE TITLE
 Parser.cs(ReadXRefStream()): Is Debug.Assert(generation == 0) neccessary?

### ISSUE THREAD

**Issue by Jambofi76** [empira/PDFsharp-1.5#52]
Parser.cs/ReadXRefStream(): Is the line 1189 **Debug.Assert(generation == 0)** really necessary?

In my PDF file there is an XRef stream object with generation 1.
168 1 obj
<</DecodeParms <</Columns 5/Predictor 12>>/Filter /FlateDecode/ID [(K\267M\221U\321\254>\315\377,Q\372\207KL) (K\267M\221U\321\254>\315\377,Q\372\207KL)]/Info 1 0 R/Length 329/Root 2 0 R/Size 176/Type /XRef/W [1 3 1]>>
stream

**Comment by TH-Soft** [comment]
`Debug.Assert` does nothing in Release build, so no `Debug.Assert` is really necessary.

This one probably just indicates that the developer did not have a PDF with generation != 0 while testing this new feature.

I didn't check the PDF Reference yet. I assume generation can have any value.

**Comment by ThomasHoevel** [comment]
PDF Reference shows in 3.4.6 Object Streams:
"Any PDF object can appear in an object stream, with the following exceptions: [...]
Objects with a generation number other than zero"

The ISO specs are somewhat softer, 7.5.7 Object streams:
"The following objects shall not be stored in an object stream: [...]
Objects with a generation number other than zero"

So this Debug.Assert was written at a time when when generation numbers other than 0 could not appear in object streams.
