### ISSUE TITLE
Error 'Object already in table' on PdrReader.Open(FileName, pdfDocumentOpenMode.Import)

### ISSUE THREAD

**Issue by polarissno** [empira/PDFsharp-1.5#56]
I get this error when trying to open the included pdf using this command. I am trying to open this file to combine with other files.

PdrReader.Open(FileName, pdfDocumentOpenMode.Import)

Object already in table

[PDFsharp-IssueSubmission.zip](https://github.com/empira/PDFsharp/files/2022572/PDFsharp-IssueSubmission.zip)

Thanks.

# Resources

The official project web site:  
http://pdfsharp.net/

The official peer-to-peer support forum:  
http://forum.pdfsharp.net/

# Reporting an Issue Here
## Steps to Reproduce the Behavior
We strongly recommend using the IssueSubmissionTemplate to make sure we can replicate the issue.  
http://www.pdfsharp.net/wiki/IssueSubmissions.ashx

**Comment by ThomasHoevel** [comment]
There are two objects with ID 25 in the PDF file. When I use "Save as" in Adobe Reader I get a PDF file without duplicate objects.

Adobe Reader does a good job with respect to opening and fixing corrupted PDF files where PDFsharp just throws an exception. Looks as if PDFsharp is working as intended.

**Comment by polarissno** [comment]
Thank you for the quick response. I will Try that

"In theory, theory and practice are the same. In practice, they are not."

**Comment by polarissno** [comment]
Thank you for the quick response. I will try that. 

"In theory, theory and practice are the same. In practice, they are not."

**Comment by smiles3983** [comment]
Is there a way to only open one object using PDFSharp?
