### ISSUE TITLE
Paging in Footer like Page x of y.

### ISSUE THREAD

**Issue by mkrishna2025** [empira/PDFsharp-1.5#58]
I didnt find any documentation to implement paging in footer.

**Comment by TH-Soft** [comment]
It is very simple: You call the DrawString method of the XGraphics class for every page with the footer text you want to have on that page.

See MigraDoc for a more sophisticated solution that supports automatic page breaks, headers, footers, and some more Word-like features.

**Comment by mkrishna2025** [comment]
Actually I am using PDFSharp and not MigraDoc.. Can we get in pdfsharp ?

**Comment by mkrishna2025** [comment]
Actually I am using PDFSharp and not MigraDoc.. Can we get in pdfsharp ?

**Comment by mkrishna2025** [comment]
I am using below line for generating pdf .. How can we get same thing with MigraDoc ?
PdfDocument pdf = TheArtOfDev.HtmlRenderer.PdfSharp.PdfGenerator.GeneratePdf(html.ToString(), PageSize.A4);

**Comment by TH-Soft** [comment]
You are not using PDFsharp. Contact the makers of HTML Renderer for help.

**Comment by mkrishna2025** [comment]
we can do this in PDFSharp with HTML Renderer too.. For any support, mail to mkrishna2025@gmail.com

**Comment by ThomasHoevel** [comment]
This is the PDFsharp repository, not the HTML Renderer repository. It is not relevant what can be done with HTML Renderer, at least not here. They have their own GitHub repository.
