### ISSUE TITLE
"Behind" should read "In Front"?

### ISSUE THREAD

**Issue by bretgourdie** [empira/PDFsharp-1.5#62]
For the summary on XGraphicsPdfPageOptions, shouldn't Append's summary tag read _"The new content is **appended in front of** the old content and any subsequent drawing in done above the existing graphic."_?

It threw me for a loop when I read _The new content is inserted behind the old content and any subsequent drawing in done above the existing graphic._ because that would be the exact opposite of an append.

https://github.com/empira/PDFsharp/blob/5aa7afeb13270aaca36ad21edcf3cc62d6c5446c/src/PdfSharp/Drawing/enums/XGraphicsPdfPageOptions.cs#L38

**Comment by TH-Soft** [comment]
In the list of drawing instructions, the new content is added behind the old content. Thus the new content is drawn later than the old content - and usually it shows in front of the new content.
You are thinking in terms of visibility, the author of the comment was thinking in terms of PDF contents.
