### ISSUE TITLE
Support for XFont to check if character is supported.

### ISSUE THREAD

**Issue by LokiMidgard** [empira/PDFsharp-1.5#64]
Not all fonts have the same glyphs. It would be nice if one could check with an method on an XFont object if a specific character has a glyph in the font. So the calling library's can change to a fallback font.

The best method I've fond was `CharCodeToGlypheIndex`. If this returns `0` no glyph was found. But this method is only internal accessible. So calling library's can't use this.

**Comment by ThomasHoevel** [comment]
The name of the method is `CharCodeToGlyphIndex` and it is `public`. However the class is `internal`.

https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/Fonts.OpenType/OpenTypeDescriptor.cs#L307

**Comment by LokiMidgard** [comment]
Yes, but it is in `OpenTypeDescriptor` and the property `Descriptor` in `XFont` is marked as internal.
 So I can't acces the public method.

**Comment by ThomasHoevel** [comment]
Here's an extension method that works with PDFsharp 6.x:

```
public static class FontHelper
{
    /// <summary>
    /// Returns true if the font supports all glyphs in the string.
    /// Returns false if at least one character could not be found.
    /// Method works for regular fonts, but not for symbol fonts.
    /// </summary>
    /// <param name="font"></param>
    /// <param name="s"></param>
    /// <returns></returns>
    public static bool HasGlyph(this XFont font, string s)
    {
        for (int idx = 0; idx < s.Length;)
        {
            var c = Char.ConvertToUtf32(s, idx);
            var x = GlyphHelper.GlyphIndexFromCodePoint(c, font);
            if (x == 0)
                return false;

            // Increment index depending on char that was found.
            if (c > 65535)
                idx += 2; // Unicode char was not from the BMP, so assume it uses two .NET Chars.
            else
                ++idx; // Unicode characters from the BMP fit into a single .NET Char.
        }

        return true;
    }
}
```

Here is a sample call:
`bool test = font.HasGlyph("€💩");`

Result is true if all characters are supported by a given font, or false if at least one character is not supported.

I did not check if the code also works with PDFsharp 1.5.
