### ISSUE TITLE
I have a replacement for GetFontData on Linux

### ISSUE THREAD

**Issue by ststeiger** [empira/PDFsharp-1.5#65]
I have a replacement for GetFontData, which works on all platforms. 

https://gist.github.com/ststeiger/273341aebd29009f2b272b822b69563f

This uses the C# FreeType wrapper from 
https://github.com/Robmaister/SharpFont

SharpFont doesn't work on Windows x64 out of the box, this correction is requried: 
https://gist.github.com/ststeiger/9e2eb98e29a3c987aca739045af1d2ce

I think you have been working with OpenType before. 
I'm pretty sure it would be possible to remove the dependency on FreeType.

**Comment by huangxiangyao** [comment]
I have a revision of PdfSharp-MigraDoc works on Linux.
https://github.com/myvas/PdfSharpCore

All samples tested on Linux and Windows.

**Comment by ThomasHoevel** [comment]
PDFsharp 6.0.0 works on Linux.
