### ISSUE TITLE
Fixes for NetStandard-version

### ISSUE THREAD

**Issue by ststeiger** [empira/PDFsharp-1.5#66]
I've been porting the code to NetStandard. 
https://github.com/ststeiger/PdfSharpNetStandard

Could you move the code in PdfSharp.Forms and PdfSharp.Windows into a separate shared-project ? 
https://github.com/ststeiger/PdfSharpNetStandard/tree/master/PdfSharp_Removed

Also, same thing with Rendering.Forms and Rendering.Windows in MigraDoc.Rendering
https://github.com/ststeiger/PdfSharpNetStandard/tree/master/MigraDoc_Rendering_Removed

Then it would be very simple to have a NetStandard-Version. 

Also, if you used partial classes in cunjunction with a shared project for gdi and wpf, then you could get rid of all the #ifs that make the project unreadable, and also wouldn't need to symlink files.

**Comment by MovGP0** [comment]
I agree. Issues #78 and #77 should be done first.

**Comment by shashi4u** [comment]
I was playing with my own version of [.net standard 2.0 port](https://github.com/shashi4u/PDFsharp) for PDFSharp and encountered the following error in windows.

System.NotSupportedException: 'No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.'

When I added the below line in my application the error no longer appeared. **System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);**

Another solution was to add  !NETSTANDARD condition in get method of WinAnsiiEncoding in PdfEncoder.cs at line 71

`
**#if !SILVERLIGHT && !NETFX_CORE && !UWP && !NETSTANDARD**

                    // Use .net encoder if available.
                    _winAnsiEncoding = Encoding.GetEncoding(1252);
#else

                    // Use own implementation in Silverlight and WinRT
                    _winAnsiEncoding = new AnsiEncoding();
#endif
`

I only tested it in windows.
Just sharing my findings hoping it might be helpful.

**Comment by ThomasHoevel** [comment]
As of PDFsharp 6.0.0, PDFsharp is now using .NET 6.
