### ISSUE TITLE
Signing functionality

### ISSUE THREAD

**Issue by devel-pa** [empira/PDFsharp-1.5#7]
Hi,

Thank you for sharing this wonderful library.

My enterprise added a signing functionality to it and wants to contribute to your project. Before creating a pull request I need some information:
- Would you accept a pull request with this functionality?
- When the next release will be scheduled in case you'll accept the pull request?

Best,
Paul

**Comment by ThomasHoevel** [comment]
Also discussed in the PDFsharp forum:
http://forum.pdfsharp.net/viewtopic.php?f=4&t=3495
