### ISSUE TITLE
Zero-width Joiner Not Handled Properly

### ISSUE THREAD

**Issue by tbihlajama** [empira/PDFsharp-1.5#70]
Greetings,

In testing the PdfSharp package, we found that certain characters we not rendered properly.  For example, the character ප්‍ර is being rendered as ප්‍ ර. It appears to be linked to characters that use a zero-width joiner in their combination.

I've attached an example to demostrate the issue.  Thank you for any support you can provide.

Regards.

[PDFsharp-IssueSubmission.zip](https://github.com/empira/PDFsharp/files/2465469/PDFsharp-IssueSubmission.zip)

**Comment by ThomasHoevel** [comment]
Zero-width joiner and ligatures are not yet supported by PDFsharp. There is not ETA for this feature.
