### ISSUE TITLE
Is it possible to use PDFSharp to create diagrams that PSTricks can generate?

### ISSUE THREAD

**Issue by sadqiang** [empira/PDFsharp-1.5#73]
I love creating diagrams with PSTricks (that is a library of PostScript instructions wrapped for TeX users ).
I also love C#.

I am a newbie in PDFSharp. My question is

> Is it possible to use PDFSharp for drawing diagrams that PSTricks  can produce?

Please navigate to [this link](http://tug.org/PSTricks/main.cgi?file=Examples/Gallery3D/Gallery3D) to know what PSTricks is.

**Comment by ThomasHoevel** [comment]
Here you can see some of the things PDFsharp can do (don't forget to look at the PDF):  
http://www.pdfsharp.net/wiki/Graphics-sample.ashx

Yes, it is possible. Are you volunteering to implement it?

**Comment by sadqiang** [comment]
Thank you for your response. It is interesting but I have no plan to  implement it soon. :-)
