### ISSUE TITLE
Don't use #if statements instead of System.Diagnostics.Conditional 

### ISSUE THREAD

**Issue by MovGP0** [empira/PDFsharp-1.5#77]
## Expected Behavior

Conditional code should be marked with the `[Conditional("FOO")]` attribute, instead of using `#if FOO` everywhere. This way the compiler can check the code even when the attribute is not set. 

## Actual Behavior

`#if FOO` is cluttered everywhere in the codebase

## Steps to Reproduce the Behavior

read the source code. 

## Resources

* [ConditionalAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute)

**Comment by ThomasHoevel** [comment]
Good point, but PDFsharp will stick to `#if` for now.
